config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :comments
  resources :lessons
  resources :users
  
  root 'sessions#new'
  get "/bestuser", to: "users#best_users", as: "best_users"

  resources :users do
    resources :lessons, only: [:new, :create, :index, :show]
  end

  resources :lessons do
    resources :ratings, only: [:new, :create, :index, :show]
  end

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/' => 'sessions#new'
  post '/' => 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_many :lessons
    has_many :users, through: :lessons    
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :user
    belongs_to :comment
    has_many :ratings
    accepts_nested_attributes_for :comment
    validate :title_content

    scope :search_by_title, -> (search_title){where("title = ?", search_title)}

    def title_content
        if [self.title, self.content].reject(&:blank?).size == 0
          errors[:base] << ("Please submit title and content.")
        end
    end  
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :lesson
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :lessons
    has_many :comments, through: :lessons

    validates :name,  uniqueness: true
    validates :name,  presence: true
    validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.name = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

    def new
      @lesson = Lesson.new
      @lesson.build_comment
    end

    def create
        @lesson = current_user.lessons.build(lesson_params)
          if @lesson.save
           # redirect_to lesson_path(@lesson)
           render json: @lesson
          else
            render :new
          end
    end

    def show
        @lesson = Lesson.find_by(id: params[:id])
        respond_to do |f|
          f.html
          f.json {render json: @lesson}
        end
    end

    def index
      if params[:user_id]
        @lessons = User.find(params[:user_id]).lessons
      elsif params[:title]
        @lessons = Lesson.search_by_title(params[:title])
      else
        @lessons = Lesson.all
        respond_to do |f|
          f.html
          f.json {render json: @lessons}
        end
      end
    end



    def edit
      @lesson = Lesson.find_by(id: params[:id])
    end
  
    def update
      @lesson = Lesson.find_by(id: params[:id])
      if @lesson.update(lesson_params)
        redirect_to lesson_path(@lesson)
      else
        render :edit
      end
    end
  
    def destroy
      @lesson = Lesson.find_by(id: params[:id])
      @lesson.destroy
      redirect_to user_path(current_user)
    end

    private

    def lesson_params
        params.require(:lesson).permit(:title, :content, comment_attributes: [:text])
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

	def new
		@lesson = Lesson.find(params["lesson_id"])
		@rating = @lesson.ratings.build
	end
	
	def create
		@lesson = Lesson.find(params["lesson_id"])
		@rating = @lesson.ratings.build
		if @rating.update(rating_params)
			respond_to do |format|
				format.html {redirect_to lesson_path(@lesson)}
				format.json {render json: @rating}
			end
		else
			flash.now[:message] = @rating.errors[:content][0]
			render :new
		end
    end
    
    private
    def rating_params
        params.require(:rating).permit(:lesson_id, :stars)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
    @user = User.new
  end

def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :error
    end
  end
  
def destroy
  if !session[:user_id].nil?
      session[:user_id] = nil
  end
    redirect_to '/'
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
    def new
        @user = User.new
    end
    
    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:errors] = @user.errors.full_messages	
        render :error2
      end
    end
    
    def show
      @user = User.find_by(:id => params[:id])
     if  @lesson = Lesson.find_by(id: params[:id])
      @lesson.user.id = @user.id
     end
    end
  

    def best_users
      @users = User.joins(:lessons).group(:id).order('COUNT(lessons.id) DESC').limit(5)
    end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if @lesson.errors.any? %>
  <div class = "fields_with_errors">
    <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being created:</font></h2>
    <ul>
    <% @lesson.errors.full_messages.each do |msg| %>
      <li><em><%= msg %><em></li></br>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnFullstackApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_aside.html.erb
<aside class="sidebar">
<nav class="nav">
  <ul>
    <li><%= link_to 'Homepage', user_path(current_user.id)%></li>
    <li><%= link_to 'All Lessons', lessons_path %></li>
    <%= form_tag("/lessons", method: "get") do %>
      <li class ="search"><%= label_tag(:title, "Search lesson by title:") %></li>
      <%= text_field_tag(:title) %></br></br>
        <%= submit_tag("Search") %>
      <% end %>
  </ul>
</nav>
</aside>

app/views/lessons/_form.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<% if logged_in? %>
<main class="main">
  <aside class="sidebar">
    <nav class="nav">
      <ul>
        <li><%= link_to 'Homepage', user_path(current_user.id)%></li>
        <li><%= link_to 'All Lessons', lessons_path %></li>
      </ul>
    </nav>
  </aside>
  <section class="twitter">
    <div class="container">
    <div class = "fields_with_errors"><%= render 'layouts/errors' %></div>
    <%= form_for @lesson do |f| %>
        <div class="p">
        <%= f.label :title%></br>
        <%= f.text_field :title %>
        </div></br>
        <div class="p">
        <%= f.label :content%></br>
        <%= f.text_area(:content, size: "33x5")  %>
        </div></br>
        <div class="p">
        <%= f.fields_for :comment do |v|%>
            <%= v.label :comment%></br>
            <%= v.text_area(:text, size: "33x3") %>
        <% end %>
        </div>
    <div class="p">
    <%= f.submit %>
    </div>
    <br><br>
    <% end %>
    </div>
  </section>
</main>
<% end %>

app/views/lessons/edit.html.erb
<%= render 'form' %>

app/views/lessons/index.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<% if logged_in? %>
<main class="main">
<%= render 'aside' %>
  <section class="twitter allign">
    <% @lessons.each do |lesson|  %>
      <p class="creator">Author:<p>
      <p class="author"><%= lesson.user.name %></p>
      <p class="p">Lesson title:</p>
      <p class="subs title"><%= link_to lesson.title, lesson_path(lesson) %></p>
      <p class="p">Lesson content: </p>
      <p class="subs2"><%= lesson.content %></p>
      <p class="p">Lesson comment: </p>
      <p class="subs"><%= lesson.comment.text %></p>
      <% if lesson.ratings.empty?  %>
      <p class="p">There are no ratings yet.</p>
        <% else %>
        <p class="p">Lesson Rating: </p>
        <% lesson.ratings.each do |rate|  %>
          <p class="subs">*<%= rate.stars %></p>
        <% end %>
      <% end %>
      <p class="p"><%= link_to "-> New rating <-", new_lesson_rating_path(lesson.id)%></p>
      </br></br>
      <% end %>
  </section>
</main>
<% end %>

app/views/lessons/new.html.erb
<%= render 'form' %>

app/views/lessons/show.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<% if logged_in? %>
<main class="main">
<%= render 'aside' %>
  <section class="twitter allign2">
    <p class="creator">Author:<p>
    <p class="author"><%= @lesson.user.name %></p>
    <p class="p">Lesson title:</p>
    <p class="subs title"><%= @lesson.title %></p>
    <p class="p">Lesson content: </p>
    <p class="subs"><%= @lesson.content %></p>
    <p class="p">Lesson comment: </p>
    <p class="subs"><%= @lesson.comment.text %></p>
      <% if @lesson.ratings.empty?  %>
      <p class="p">There are no ratings yet.</p>
        <% else %>
        <p class="p">Lesson Rating: </p>
        <% @lesson.ratings.each do |rate|  %>
          <p class="subs">*<%= rate.stars %></p>
        <% end %>
      <% end %>
      <p class="p"><%= link_to "-> New rating <-", new_lesson_rating_path(@lesson.id)%></p>
      <% if current_user.id === @lesson.user.id %>
      <p class="p"><%= link_to "Edit Lesson", edit_lesson_path(@lesson)%></p>
      <p class="p"><%= link_to "Delete Lesson", lesson_path(@lesson), method: :delete%></p>
      <% end %>      
  </section>
</main>
<% end %>

app/views/ratings/new.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<% if logged_in? %>
<main class="main">
<%= render 'lessons/aside' %>
  <section class="twitter">
    <div class="container">
	  <p>New rating form</p>
	  <%= form_for [@lesson, @rating] do |f| %>
		<p><%= f.number_field :stars, min:0, max:10  %></p>
		<%= f.submit %>
	  <% end %>
    </div>
  </section>
</main>
<% end %>

app/views/ratings/show.html.erb
<h1>Rating show</h1>

<p>This is a rating on the following lesson: </p>
<h3><%= @rating.lesson.title %></h3>
<%= @rating.lesson.content %>
<hr>
<p>Rating:</p>
<%= @rating.content %>

app/views/users/best_users.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<% if logged_in? %>
<main class="main">
<%= render 'lessons/aside' %>
  <section class="twitter allign2">
    <% @users.each do |user|  %>
      <p class="p">Author:</p>
      <p class="author"><%= user.name %></p>
      <p class="p">Number of lessons created:</p> 
      <p class="author"><%= user.lessons.count %></p>
    <% end %> 
  </section>
</main>
<% end %>

app/views/users/error2.html.erb
<%= button_to "Back", root_url, :method => :get %>
<div id="action-container2";>
  <div class="action">
    <h1>Sign Up</h1>
    <% if !!flash[:errors] %>
    <% flash[:errors].each do |e| %>
      <p style="color:red;"><i><%= e %></i></p> 
      <% end %>
    <% end %>
    <div>
      <%= form_for(@user)  do |f| %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </p>
        <p>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </p>
        <p>
          <%= f.submit "Sign Up", :class => 'boost-btn btn-primary btn-sm btn-block' %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<div class="home-video-wrapper">
  <%= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "home_video" %>
</div>

app/views/users/show.html.erb
<%=  stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true %>

<main class="main">
  <aside class="sidebar">
    <nav class="nav">
      <ul>
        <li class="active"><a>Welcome <%= current_user.name %></a></li>
        <li><%= link_to 'All Lessons Rails', lessons_path %></li>
        <li><%= link_to 'All Lessons Ajax', lessons_path, class: "all_lessons" %></li>
        <li><%= link_to 'Create Lesson', new_user_lesson_path(current_user) %></li>
        <li><%= link_to "Top Lesson Creators", best_users_path %></li>

        <li class="index_link"><a href="http://localhost:3000/lessons">index sort link</a></li>

        <li class="active"><%= link_to "Log Out", signout_path, method: :delete %></li>
      </ul>
    </nav>
  </aside>
  <section class="twitter allign4">
        <p id="app-container"></p>
  </section>
</main>